BEGIN TRANSACTION;

CREATE TABLE orders (
  id serial PRIMARY KEY,
  userid INTEGER NOT NULL,
  price FLOAT NOT NULL,
  isdelivered BOOLEAN DEFAULT FALSE,
  date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  products JSON NOT NULL
);

COMMIT;